### ISSUE TITLE
Can't update record

### ISSUE THREAD

**Issue by github4touchdouble** [carlobortolan/Embloy#12]
something like user.update!(first_name: "Testname") will raise an exception from the password validator.

`({:password=>[{:error=>"ERR_BLANK", :description=>"Attribute can't be blank"}, {:error=>:too_short, :count=>8}]})`

It is totally confusing why the password validator cries after the account was created AND when trying to edit/update something totally different

**Comment by carlobortolan** [comment]
# Funktioniert 
        @user.update_column("email", "carlobortolan@gmail.com")
        # Funktioniert *NICHT*
        @user.update(email: "carlobortolan@embloy.com")
