### ISSUE TITLE
Centralized Exception Service

### ISSUE THREAD

**Issue by github4touchdouble** [carlobortolan/Embloy#19]
Centralize & Standardize the definition of custom exceptions.

This must include a substantial documentation. (Every developer working on the backend will need to throuw the correct exception at the correct moment)

**Comment by carlobortolan** [comment]
- Added  [CustomExceptions](https://github.com/carlobortolan/Embloy/blob/master/app/service/custom_exceptions.rb) class:
  - InvalidUser (Current.user.nil, User deactivated, no record for a given ID, ...)
  - Unauthorized (User does not have the required role to access resource)
  - InvalidInput (Token malformed / expired)

- Renamed `::Taboo` to `::InsufficientRole`
- Refactored `user_role.rb` ,`authentication_token_service.rb` as well as controllers in `api/v0/...`
- Added basic documentation [here](https://github.com/carlobortolan/Embloy/blob/master/app/service/custom_exceptions_doc.md)
